name: Suggestions
description: For suggesting changes / additions / mods
title: "[Suggestion]: "
labels: [suggestion]
body:
  - type: checkboxes
    id: general-info
    attributes:
      label: General Info
      description: You may select more than one.
      options:
        - label: I would like to suggest a new mod
        - label: I would like to suggest a new quests
        - label: I would like to propose changes
        - label: I would like to propose another thing
    validations:
      required: false
  - type: textarea
    id: suggestion-description
    attributes:
      label: Suggestion Description
      description: Tell us your suggestion
      placeholder: I want ...
    validations:
      required: true
